MVCExtension.Points/Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading;
using System.Web.Mvc;
using MVCExtension.Points.Extensions;
using MVCExtension.Points.Models;
using MVCExtension.Points.Providers;

namespace MVCExtension.Points.Controllers
{
    public class ServiceController : Controller
    {
        private readonly IUserProvider _userProvider;

        public ServiceController(IUserProvider userProvider)
        {
            _userProvider = userProvider;
        }

        
        //public void GetUser()
        //{
        //    var user = new UserViewModel()
        //    {
        //        Name = "richie",
        //        Age = 20,
        //        Email = "abc@126.com",
        //        Phone = "139********",
        //        Address = "my address"
        //    };
        //    XmlSerializer serializer = new XmlSerializer(typeof(UserViewModel));
        //    Response.ContentType = "text/xml";
        //    serializer.Serialize(Response.Output, user);
        //}

        //1.example of ActionResult extension
        public XmlResult GetUser()
        {
            var user = new UserViewModel()
            {
                Name = "richie",
                Age = 20,
                Email = "abc@126.com",
                Phone = "139********",
                Address = "my address"
            };

            return new XmlResult(user);
        }

        //example of ActionResult extension
        public CsvResult DownloadUser()
        {
            var user = new UserViewModel()
            {
                Name = "richie",
                Age = 20,
                Email = "abc@126.com",
                Phone = "139********",
                Address = "my address"
            };

            return new CsvResult(new List<UserViewModel>() { user }, "user");
        }

        //2.example of IExceptionFilter extension
        public ActionResult ThrowException()
        {
            throw new InvalidDataException("throw some exceptions...");
        }

        //3.example of htmlHelper extension
        public ActionResult GetProducts()
        {
            var products = new ProductListViewModel()
            {
                FoodProducts = new List<ProductListViewModel.Product>()
                {
                    new ProductListViewModel.Product("Popcorn",""),
                    new ProductListViewModel.Product("Coke",""),
                    new ProductListViewModel.Product("Egg",""),
                    new ProductListViewModel.Product("Meet","")
                },
                BookProducts = new List<ProductListViewModel.Product>()
                {
                    new ProductListViewModel.Product("c#",""),
                    new ProductListViewModel.Product("java",""),
                    new ProductListViewModel.Product("swift",""),
                    new ProductListViewModel.Product("c++","")
                },
                SportProducts = new List<ProductListViewModel.Product>()
                {
                      new ProductListViewModel.Product("Basketbal",""),
                    new ProductListViewModel.Product("Football",""),
                    new ProductListViewModel.Product("Table tennis ball",""),
                    new ProductListViewModel.Product("Badminton","")
                }
            };
            return View(products);
        }

        //4.example of ViewEngine extension
        public ActionResult SomeView()
        {
            return View();
        }

        //5.example of Model validator extension
        public ActionResult InputAge()
        {
            return View();
        }
            
        [HttpPost]
        public ActionResult InputAge(UserViewModel user)
        {
            if (ModelState.IsValid)
            {
                return View("SaveAge",user);
            }

            return View();
        }

        //6.example of xml model binder extension
        //public ActionResult PostXmlContent([ModelBinder(typeof(XmlModelBinder))]UserViewModel user)
        //{
        //    return new XmlResult(user);
        //}

        public ActionResult PostXmlContent(UserViewModel user)
        {
            return new XmlResult(user);
        }

        //7.example of Controller Factory extension
        public ActionResult GetUserByIoc()
        {
            var user = _userProvider.GetUser();
            return new XmlResult(user);
        }

        //8.example of Lambda Tree helper
        public ActionResult Orders()
        {
            return View();
        }

        public ActionResult OrderLineItem(int id)
        {
            return View(id);
        }

        //example of value provider extension
        public ActionResult SaveUser(UserViewModel user)
        {
            //user.Host = Request.Host;
            return Content(user.Host);
        }

       
    }
}

MVCExtension.Points/Views/Service/GetProducts.cshtml
@using MVCExtension.Points.Extensions
@using MVCExtension.Points.Models
@model MVCExtension.Points.Models.ProductListViewModel

@{
    ViewBag.Title = "Product list";
}

<h2>Product list using helper</h2>
<div class="row">
    <div class="col-md-6">@ShowProduct(Model.SportProducts, "list-group-item-info")</div>
    <div class="col-md-6">@ShowProduct(Model.BookProducts, "list-group-item-warning")</div>
</div>
<div class="row">
    <div class="col-md-6">@ShowProduct(Model.FoodProducts, "list-group-item-danger")</div>
</div>

<h2>Product list using htmlHelper</h2>
<div class="row">
    <div class="col-md-6">@Html.ListGroup().Info(Model.SportProducts,x=>x.Name)</div>
    <div class="col-md-6">@Html.ListGroup().Warning(Model.BookProducts,x => x.Name)</div>
</div>
<div class="row">
    <div class="col-md-6">@Html.ListGroup().Danger(Model.FoodProducts,x => x.Name)</div>
</div>


@helper ShowProduct(List<ProductListViewModel.Product> products, string style)
{
    <ul class="list-group">
        @foreach (var product in products)
        {
            <li class="list-group-item @style"><a href="@product.Href" target="_blank">@product.Name</a></li>
        }
    </ul>
}

MVCExtension.Points/Views/Service/InputAge.cshtml
@model MVCExtension.Points.Models.UserViewModel

@{
    ViewBag.Title = "input age";
}

<h2>Input age</h2>
@using (Html.BeginForm("InputAge", "Service", FormMethod.Post, new { @class = "form" }))
{
    <div class="col-md-12">
        @Html.ValidationSummary()
    </div>
    <div class="input-group">
        <span class="col-md-4">@Html.LabelFor(x => x.Name)</span>
        @Html.TextBoxFor(x => x.Name, new {@class = "form-control"})
    </div>

    <div class="input-group">
        <span class="col-md-4">@Html.LabelFor(x => x.Age)</span>
        @Html.TextBoxFor(x => x.Age, new { @class = "form-control" })
    </div>

    <div class="col-md-12">
        <input type="submit" class="btn btn-primary pull-right" value="submit!" />
    </div>

}

MVCExtension.Points/Views/Service/OrderLineItem.cshtml
@model int

<h2>Order line item id:@Model</h2>

MVCExtension.Points/Views/Service/Orders.cshtml
@using MVCExtension.Points.Controllers
@using MVCExtension.Points.Extensions.Helpers
<h3>Orders</h3>
<div class="row">
    <h2>Mvc way</h2>
    <ul>
        <li>@Html.ActionLink("Line item 1", "OrderLineItem", "Service", new { id = 1 }) </li>
        <li>@Html.ActionLink("Line item 2", "OrderLineItem", "Service", new { id = 2 })</li>
        <li>@Url.Action("OrderLineItem","Service",new {id=1})</li>
        <li>@Url.Action("OrderLineItem","Service",new {id=2})</li>
    </ul>
</div>

<div class="row">
    <h2>Lambda Expression tree</h2>
    <ul>
        <li>@Html.ActionLink("Line item 1", (ServiceController c) => c.OrderLineItem(1))</li>
        <li>@Html.ActionLink("Line item 2", (ServiceController c) => c.OrderLineItem(2))</li>
        <li>@Url.Action((ServiceController c)=>c.OrderLineItem(1))</li>
        <li>@Url.Action((ServiceController c)=>c.OrderLineItem(2))</li>
    </ul>
</div>

MVCExtension.Points/Views/Service/SaveAge.cshtml
@model MVCExtension.Points.Models.UserViewModel

@{
    ViewBag.Title = "input age successful";
}

<h2>your age is :@Model.Age</h2>

MVCExtension.Points/Views/Service/SomeView.cshtml
@{
    ViewBag.Title = "some view";
}

<h2>this is someview in service folder</h2>